services:
  db:
    container_name: "db_ranked"
    image: "mariadb:11.4"
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-13306}:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    container_name: "phpmyadmin_ranked"
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PMA_PORT:-8080}:80"

  mailpit:
    container_name: "mailpit_ranked"
    image: axllent/mailpit:latest
    restart: on-failure
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"

volumes:
  mariadb_data: