sonar.projectKey=RankED-2025_ranked
sonar.organization=ranked-2025
sonar.projectName=RankED
sonar.sourceEncoding=UTF-8

# Sources des deux modules
sonar.sources=back/src,front/src
sonar.tests=back/tests,front/src

# Coverage
sonar.php.coverage.reportPaths=back/coverage/coverage.xml
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info

# Exclusions
sonar.exclusions=\
  back/var/**,\
  back/vendor/**,\
  back/public/**,\
  back/config/**,\
  back/migrations/**,\
  back/bin/**,\
  front/node_modules/**,\
  front/dist/**