sonar.projectKey=RankED-2025_ranked
sonar.organization=ranked-2025
sonar.projectName=RankED

sonar.sources=back/src,front/src
sonar.tests=back/tests,front/tests

sonar.php.coverage.reportPaths=back/build/logs/clover.xml
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info

sonar.exclusions=**/vendor/**,**/var/**,**/migrations/**,**/dist/**,**/coverage/**,**/node_modules/**
sonar.sourceEncoding=UTF-8