sonar.projectKey=RankED-2025_ranked
sonar.organization=ranked-2025
sonar.projectName=RankED

sonar.sourceEncoding=UTF-8

# Modules
sonar.modules=back,front

# --- Back (Symfony) ---
back.sonar.projectBaseDir=back
back.sonar.sources=src
back.sonar.tests=tests
back.sonar.php.coverage.reportPaths=coverage/coverage.xml

# --- Front (VueJS) ---
front.sonar.projectBaseDir=front
front.sonar.sources=src
front.sonar.tests=src
front.sonar.javascript.lcov.reportPaths=coverage/lcov.info
front.sonar.exclusions=node_modules/**