sonar.projectKey=YOUR_BACK_PROJECT_KEY
sonar.organization=YOUR_ORG_KEY
sonar.projectName=RankED Back
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.exclusions=vendor/**,var/**,migrations/**
sonar.sourceEncoding=UTF-8
