sonar.projectKey=RankED-2025_ranked
sonar.organization=RankED-2025
sonar.projectName=RankED Back
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.exclusions=vendor/**,var/**,migrations/**
sonar.sourceEncoding=UTF-8
